---
spec/spec_helper.rb:
  mock_with: ":mocha"
.travis.yml:
  user: "optiz0r"
  secure: "tvNiHRd7R7Y0AEErTM79jYOeGKb8YCohNEU1jXpXlJ4Cr9eibRG3P3BEm7dNNt+/yiosnR/PBupdt+kCI/3VuscR3GZR0pZdK36/m2VRzvNFmCDCoy8MVEiINM6TI5L34F/lhqKByu6mGyLEWwp8HGzD8qbQR6kejAyGSSGphwl+q6jH++ZnQUNAK1pbgkrlfXWpVLn9fNzpkOaK6ysRIWqXoUntQLsQvKv2sMU4PJJ/qKHV7F3l1ZYJ9ZGRpqJCnRKpoE+5nZTHrpaU5nLRnE6d4Ud9nTGxHEh+ozq2Up+8s7QiR721g44L9TJ4hNvwSVWrpRfK0bmN0stZPeW1ln9YqviQsRAHuwF2L81eLAINB/MjOepHc/wQsv0La15bZ/nAvqZ8DG9FSxG5djnr3ycLewmZlupfujSS3eOmL7Yw3KMIfVNcEwtRrPd/QQiBQn3LFZMMYTIDM6n4LhCZ+qf7/lxbr8HhTrUtzzx3DN6sEWNR1GxFbQvJmRkpMRRAZHmcwYPBfReIVpJErjed8ytbGDE2DxQroZjv064t55xrEiNSwB8WblZA2fiIicR/p+E3lGuG8URD9ZEv3AxVWpNNwwV4+8Q6A+hdQlX1FW1dNRVjf2rB4iwIChkLZ2tX9B15W+k9HVFE+1zrbwXByYOMMcPUZs6E01t1Z7mFevo="
